# Generated by Django 3.2 on 2022-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_contacted', models.DateField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('query', models.TextField(max_length=255)),
            ],
        ),
    ]
