# Generated by Django 3.2 on 2022-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=255)),
            ],
        ),
    ]
