# Generated by Django 3.2 on 2022-04-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
