# Generated by Django 3.2 on 2022-03-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrequest',
            name='type',
            field=models.ForeignKey(default=1, on_delete=models.SET('Deleted Genre'), to='commission.genre'),
            preserve_default=False,
        ),
    ]
