# Generated by Django 3.2 on 2022-04-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_comment_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='archived',
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
