# Generated by Django 3.2 on 2022-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_commissionrequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
