# Generated by Django 3.2 on 2022-03-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_commissionrequest_date_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionrequest',
            old_name='user_desc',
            new_name='user_description',
        ),
    ]
