# Generated by Django 3.2 on 2022-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0004_rename_user_desc_commissionrequest_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrequest',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('ORDR', 'Ordered'), ('URWE', 'Under Review'), ('ACPD', 'Accepted'), ('DECL', 'Declined'), ('IPRR', 'In progress'), ('DONE', 'Done'), ('USRW', 'User review')], default='PEND', max_length=4),
        ),
    ]
