# Generated by Django 3.2 on 2022-03-26 21:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentry',
            name='water_marked_image',
            field=cloudinary.models.CloudinaryField(default='no_image', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
