# Generated by Django 3.2 on 2022-04-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_imageentry_water_marked_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageentry',
            old_name='hidden',
            new_name='is_hidden',
        ),
    ]
