# Generated by Django 3.2 on 2022-03-09 16:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_entry_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_entry',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
