# Generated by Django 3.2 on 2022-03-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commission', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
            ],
            options={
                'verbose_name': 'Image order info entry',
                'verbose_name_plural': 'Image order info',
            },
        ),
        migrations.CreateModel(
            name='RequestOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('request_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_order', to='commission.commissionrequest')),
            ],
            options={
                'verbose_name': 'Request order info entry',
                'verbose_name_plural': 'Request order info',
            },
        ),
        migrations.CreateModel(
            name='ImageOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_lineitem_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.imageentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_lineitems', to='checkout.imageorderinfo')),
            ],
        ),
    ]
