# Generated by Django 3.2 on 2022-03-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0002_imageentry_water_marked_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='ImageOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_lineitem_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.imageentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.imageorderinfo')),
            ],
        ),
    ]
