# Generated by Django 3.2 on 2022-03-29 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_auto_20220329_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageorderinfo',
            name='user',
            field=models.ForeignKey(blank=models.SET(1), on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestorderinfo',
            name='user',
            field=models.ForeignKey(blank=models.SET(1), on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
    ]
