# Generated by Django 3.2 on 2022-03-29 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0005_alter_imageorderinfo_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageorderinfo',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='imageorderinfo',
            name='user',
            field=models.ForeignKey(default=2, on_delete=models.SET(2), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestorderinfo',
            name='user',
            field=models.ForeignKey(default=2, on_delete=models.SET(2), to=settings.AUTH_USER_MODEL),
        ),
    ]
