# Generated by Django 3.2 on 2022-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_requestorderinfo_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageorderinfo',
            name='order_id',
            field=models.CharField(editable=False, max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='requestorderinfo',
            name='order_id',
            field=models.CharField(max_length=34, unique=True),
        ),
    ]
